name: Terraform CI - CD Deployment
# trigger - when it should happen
on:
    push:
        branches:
            - master

env:
    AWS_ACCESS_KEY_ID: ${{ AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ AWS_SECRET_ACCESS_KEY }}
    AWS_SESSION_TOKEN: ${{ AWS_SESSION_TOKEN }}
    AWS_REGION: ${{ AWS_REGION }}

jobs:
    provision-infrastructure:
        name: provision-infra-using-terraform
        runs-on: ubuntu-latest

    steps:
        -   name:   Checkout Repository
            uses:   actions/checkout@v2

        -   name: Setting up the terraform
            uses: hashicorp/setup-terrform@v1
            with:
              terrform_version: 1.12.0
                
        -   name:  Terraform init
            run:  terrfaorm init

        -   name: Terraform format
            run:  terraform fmt

        -   name: Terraform Plan
            run:  terraform plan

        -   name: Terraform Apply
        run:  terrform apply